### ISSUE TITLE
java.lang.StackOverflowError when decode bad json data from body using json4s

### ISSUE THREAD

**Issue by dong77** [finagle/finch#544]
I'm using finch 0.9.3 and json4s to decode/encode json data and provided my customized Formats as follows:

```

import com.hejinonline.silk.thrift._
import com.twitter.util._
import org.json4s._
import org.json4s.native._
import io.finch._
import org.slf4j._

package object silk {
  val log = LoggerFactory.getLogger(this.getClass)

  implicit lazy val formats = silk.magic.ScroogeFormats()

  // JSON encoding/decoding related
  implicit def decodeJson[A: Manifest](implicit formats: Formats): DecodeRequest[A] =
    DecodeRequest.instance(input => Try(JsonMethods.parse(input, false).extract[A]))

  implicit def encodeJson[A <: AnyRef](implicit formats: Formats): EncodeResponse[A] =
    EncodeResponse.fromString[A]("application/json") { writeJson(_) }

  private def writeJson[A <: AnyRef](a: A)(implicit formats: Formats): String = {
    val cleaned = Extraction.decompose(a)(formats)
    Serialization.write(removeHeadAndTail(cleaned))
  }
}
```
When I submit bad json data as HTTP body, finch throws StackOverflowError:

```
E 0226 09:25:32.829 THREAD67: Exception propagated to the root monitor!
java.lang.StackOverflowError
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:164)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:164)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:164)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:164)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.orElse(PartialFunction.scala:164)
	at org.json4s.Formats$$anonfun$customSerializer$1.apply(Formats.scala:159)
	at org.json4s.Formats$$anonfun$customSerializer$1.apply(Formats.scala:158)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.json4s.Formats$class.customSerializer(Formats.scala:158)
	at org.json4s.Formats$$anon$3.customSerializer(Formats.scala:79)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:118)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.addField$1(Extraction.scala:114)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:144)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
```

I tried to give ```JsonMethods.parse(input, false).extract[A])``` in console, only one simple error was throw:

```
org.json4s.package$MappingException: No usable value for verifyCode
Did not find value which can be converted into java.lang.String
```

It doesn't seem to be a json4s issue.

**Comment by vkostyukov** [comment]
Hi @dong77! I believe I know what's going on here. Try defining `EncodeResponse[Exception]` in a way similar to [this](https://github.com/finagle/finch/blob/master/examples/src/main/scala/io/finch/eval/Main.scala#L29-L33) (but using JSON4S instead of Jackson).

**Comment by vkostyukov** [comment]
Closing this. @dong77 feel free to reopen if you still experience that problem.

**Comment by r2d2-94** [comment]
> Hi @dong77! I believe I know what's going on here. Try defining `EncodeResponse[Exception]` in a way similar to [this](https://github.com/finagle/finch/blob/master/examples/src/main/scala/io/finch/eval/Main.scala#L29-L33) (but using JSON4S instead of Jackson).

@vkostyukov I know this is an old thread, but by any chance could i get to see the snippet? I am facing this in my own project
Getting 404 on the link
