### ISSUE TITLE
ErrorDataDecoderException while posting json containing html entities `&` and `%`.

### ISSUE THREAD

**Issue by nopper** [finagle/finch#669]
I am on finch 0.10.0. Whenever I post a JSON data containing HTML entities I get an ErrorDataDecoderException (trace below). 

The same applies for finch 0.11.0-M4.

Is there a temporary workaround?

```
[error] org.jboss.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: Bad string: 'redacted'
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.decodeAttribute(HttpPos
tStandardRequestDecoder.java:525)
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.setFinalBuffer(HttpPost
StandardRequestDecoder.java:503)
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(Htt
pPostStandardRequestDecoder.java:419)
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStand
ardRequestDecoder.java:225)
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.<init>(HttpPostStandard
RequestDecoder.java:143)
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.j
ava:82)
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.j
ava:56)
[error]         at com.twitter.finagle.http.exp.Multipart$.decodeNonChunked(Multipart.scala:88)
[error]         at com.twitter.finagle.http.Request._multipart$lzycompute(Request.scala:58)
[error]         at com.twitter.finagle.http.Request._multipart(Request.scala:56)
[error]         at com.twitter.finagle.http.Request.multipart(Request.scala:55)
[error]         at io.finch.Endpoints$$anonfun$io$finch$Endpoints$$requestParam$1.apply(Endpoints.scala:235)
[error]         at io.finch.Endpoints$$anonfun$io$finch$Endpoints$$requestParam$1.apply(Endpoints.scala:235)
[error]         at scala.Option.orElse(Option.scala:289)
[error]         at io.finch.Endpoints$class.io$finch$Endpoints$$requestParam(Endpoints.scala:235)
[error]         at io.finch.Endpoints$$anonfun$paramOption$1.apply(Endpoints.scala:284)
[error]         at io.finch.Endpoints$$anonfun$paramOption$1.apply(Endpoints.scala:284)
[error]         at io.finch.Endpoints$$anonfun$io$finch$Endpoints$$option$1$$anonfun$apply$10.apply(Endpoints.scala:26
3)
[error]         at io.finch.Endpoints$$anonfun$io$finch$Endpoints$$option$1$$anonfun$apply$10.apply(Endpoints.scala:26
3)
[error]         at cats.Later.value$lzycompute(Eval.scala:148)
[error]         at cats.Later.value(Eval.scala:147)
[error]         at cats.Eval$Compute.loop$1(Eval.scala:276)
[error]         at cats.Eval$Compute.value(Eval.scala:284)
[error]         at io.finch.internal.LowPriorityToServiceInstances$$anon$1.apply(ToService.scala:66)
[error]         at io.finch.internal.LowPriorityToServiceInstances$$anon$1.apply(ToService.scala:61)
[error]         at com.twitter.finagle.ServiceProxy.apply(Service.scala:120)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.tracing.ServerDestTracingProxy$$anon$1.apply(DestinationTracing.scala:32)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.service.DeadlineFilter.apply(DeadlineFilter.scala:171)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.filter.DtabStatsFilter.apply(DtabStatsFilter.scala:37)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.service.StatsFilter.apply(StatsFilter.scala:150)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.http.filter.HttpNackFilter.apply(HttpNackFilter.scala:56)
[error]         at com.twitter.finagle.http.filter.HttpNackFilter.apply(HttpNackFilter.scala:49)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:13)
[error]         at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2$$anonfun$apply$3.ap
ply(Codec.scala:380)
[error]         at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2$$anonfun$apply$3.ap
ply(Codec.scala:380)
[error]         at com.twitter.finagle.http.TraceInfo$$anonfun$letTraceIdFromRequestHeaders$2.apply(Codec.scala:326)
[error]         at com.twitter.util.Local.let(Local.scala:141)
[error]         at com.twitter.finagle.context.Context$class.let(Context.scala:176)
[error]         at com.twitter.finagle.context.MarshalledContext.let(Context.scala:232)
[error]         at com.twitter.finagle.tracing.Trace$.letId(Trace.scala:167)
[error]         at com.twitter.finagle.http.TraceInfo$.letTraceIdFromRequestHeaders(Codec.scala:324)
[error]         at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2.apply(Codec.scala:3
80)
[error]         at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8$$anonfun$apply$2.apply(Codec.scala:3
80)
[error]         at com.twitter.util.Local.let(Local.scala:141)
[error]         at com.twitter.finagle.context.Context$class.let(Context.scala:176)
[error]         at com.twitter.finagle.context.LocalContext.let(LocalContext.scala:8)
[error]         at com.twitter.finagle.tracing.Trace$.letTracer(Trace.scala:185)
[error]         at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8.apply(Codec.scala:379)
[error]         at com.twitter.finagle.http.HttpServerTraceInitializer$$anonfun$8.apply(Codec.scala:378)
[error]         at com.twitter.finagle.Filter$$anon$6.apply(Filter.scala:217)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.filter.MonitorFilter$$anonfun$apply$1.apply(MonitorFilter.scala:35)
[error]         at com.twitter.finagle.filter.MonitorFilter$$anonfun$apply$1.apply(MonitorFilter.scala:35)
[error]         at com.twitter.util.Future$$anonfun$monitored$1.apply$mcV$sp(Future.scala:156)
[error]         at com.twitter.util.Monitor$$anonfun$apply$1.apply$mcV$sp(Monitor.scala:38)
[error]         at com.twitter.util.Monitor$$anonfun$apply$1.apply(Monitor.scala:38)
[error]         at com.twitter.util.Monitor$$anonfun$apply$1.apply(Monitor.scala:38)
[error]         at com.twitter.util.Monitor$$anonfun$using$1.apply(Monitor.scala:110)
[error]         at com.twitter.util.Monitor$.restoring(Monitor.scala:117)
[error]         at com.twitter.util.Monitor$.using(Monitor.scala:108)
[error]         at com.twitter.util.Monitor$class.apply(Monitor.scala:37)
[error]         at com.twitter.util.Future$Monitored.apply(Future.scala:163)
[error]         at com.twitter.util.Future$.monitored(Future.scala:155)
[error]         at com.twitter.finagle.filter.MonitorFilter.apply(MonitorFilter.scala:34)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.filter.PayloadSizeFilter.apply(PayloadSizeFilter.scala:29)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.http.filter.ServerContextFilter$$anonfun$apply$1.apply(ContextFilter.scala:17)
[error]         at com.twitter.finagle.http.filter.ServerContextFilter$$anonfun$apply$1.apply(ContextFilter.scala:17)
[error]         at com.twitter.finagle.http.codec.HttpContext$.read(HttpContext.scala:44)
[error]         at com.twitter.finagle.http.filter.ServerContextFilter.apply(ContextFilter.scala:17)
[error]         at com.twitter.finagle.http.filter.ServerContextFilter.apply(ContextFilter.scala:13)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
[error]         at com.twitter.finagle.http.filter.DtabFilter.apply(DtabFilter.scala:22)
[error]         at com.twitter.finagle.http.filter.DtabFilter.apply(DtabFilter.scala:11)
[error]         at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:72)
[error]         at com.twitter.finagle.http.codec.HttpServerDispatcher.dispatch(HttpServerDispatcher.scala:73)
[error]         at com.twitter.finagle.dispatch.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$dispatch$GenSer
ialServerDispatcher$$loop$1$$anonfun$apply$1.apply$mcV$sp(ServerDispatcher.scala:53)
[error]         at com.twitter.finagle.dispatch.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$dispatch$GenSer
ialServerDispatcher$$loop$1$$anonfun$apply$1.apply(ServerDispatcher.scala:52)
[error]         at com.twitter.finagle.dispatch.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$dispatch$GenSer
ialServerDispatcher$$loop$1$$anonfun$apply$1.apply(ServerDispatcher.scala:52)
[error]         at com.twitter.util.Local.let(Local.scala:141)
[error]         at com.twitter.finagle.context.Context$class.let(Context.scala:176)
[error]         at com.twitter.finagle.context.LocalContext.let(LocalContext.scala:8)
[error]         at com.twitter.finagle.dispatch.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$dispatch$GenSer
ialServerDispatcher$$loop$1.apply(ServerDispatcher.scala:51)
[error]         at com.twitter.finagle.dispatch.GenSerialServerDispatcher$$anonfun$com$twitter$finagle$dispatch$GenSer
ialServerDispatcher$$loop$1.apply(ServerDispatcher.scala:45)
[error]         at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:998)
[error]         at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:997)
[error]         at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:112)
[error]         at com.twitter.util.Promise$Transformer.k(Promise.scala:112)
[error]         at com.twitter.util.Promise$Transformer.apply(Promise.scala:122)
[error]         at com.twitter.util.Promise$Transformer.apply(Promise.scala:103)
[error]         at com.twitter.util.Promise$$anon$1.run(Promise.scala:381)
[error]         at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:178)
[error]         at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:136)
[error]         at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:207)
[error]         at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:92)
[error]         at com.twitter.util.Promise.runq(Promise.scala:350)
[error]         at com.twitter.util.Promise.updateIfEmpty(Promise.scala:721)
[error]         at com.twitter.util.Promise.update(Promise.scala:694)
[error]         at com.twitter.util.Promise.setValue(Promise.scala:670)
[error]         at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:111)
[error]         at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55)
[error]         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[error]         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultCha
....
[error] Caused by: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For 
input string: "\n"
[error]         at java.net.URLDecoder.decode(URLDecoder.java:194)
[error]         at org.jboss.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.decodeAttribute(HttpPos
tStandardRequestDecoder.java:521)
[error]         ... 183 more

```

**Comment by DieBauer** [comment]
Could you post a minimum example or test-case containing your endpoint and your input data causing the error?

**Comment by vkostyukov** [comment]
I'm closing this given there is no reproducer. @nopper please feel free to reopen if you still see this problem.
